### ISSUE TITLE
Multiple Actions per Event

### ISSUE THREAD

**Issue by mteam88** [paradigmxyz/artemis#34]
As discussed briefly on the Artemis Dev telegram channel, the current way to lauch Actions from a Strategy limits the number of Actions per Strategy run (and therefore Event) to 1.

This arbitrarily limits valid strategies that may want to launch multiple Actions as a part of one strategy. Before we have access to atomic composability with SUAVE and decentralized block building, most cross-exchange arbitrage opportunites require 1 or more legs to execute. 

Example:
In a simple CEX to DEX arbitrage transaction, there are usually two legs that need to be launched. Although it is currently possible to build this into one Action (if your Action had fields for both legs,) this seems to be **a sacrifice in composability** as future updates to the Strategy would require modifying Action and Executor. 

If multiple Actions could be spawned from the same Strategy, Actions and Executors would stay atomic. This also unlocks more **Executor level parallelism** potential, which would otherwise occur within a generalized Executor.

This change would make Artemis a better framework.

My thoughts on **how** to implement this are not yet fully developed.

**Comment by dennohpeter** [comment]
I think one way would be to make [`tx`](https://github.com/paradigmxyz/artemis/blob/34b2edcba857b36dabda83feeac14083b430c66d/crates/artemis-core/src/executors/mempool_executor.rs#L30) a vector of `TypedTransaction`

```rust
#[derive(Debug, Clone)]
pub struct SubmitTxToMempool {
    pub tx: TypedTransaction,
    pub gas_bid_info: Option<GasBidInfo>,
}
```

to

```rust
#[derive(Debug, Clone)]
pub struct SubmitTxToMempool {
    pub txs: Vec<TypedTransaction>,
    pub gas_bid_info: Option<GasBidInfo>,
}
```


And the iterating over the txs in your executor

**Comment by mteam88** [comment]
@dennohpeter I think you might misunderstand what I mean. You could do that if you needed to send only one type (`TypedTransaction`) but I was looking for a way to execute multiple *different* Actions, perhaps with different types and such.

**Comment by dennohpeter** [comment]
Oh my bad then
