### ISSUE TITLE
How to implement the delay strategy

### ISSUE THREAD

**Issue by greyireland** [paradigmxyz/artemis#44]
How to implement the delay strategy, I want to wait for the end of the block, and then send the Action to the chain, I don’t know how to implement it, do you have any suggestions?

**Comment by mteam88** [comment]
Blocks are atomic..? You can't wait for the end of a block.

**Comment by saguillo2000** [comment]
Hi @greyireland,

I don't know how you want to extract more value when the block is already written in the blockchain. Maybe what you want to make is a Frontrunning and running a PGA? 

https://cointelegraph.com/explained/what-is-front-running-in-crypto-and-nft-trading

If this is not what you meant can you please be more detalied on how you can be more profitable when a block is already written?

**Comment by greyireland** [comment]
For example, if I want to do a sandwich strategy, I want to wait until the next block of 11s is about to come out, and send a big meaty package

**Comment by JosepBove** [comment]
https://medium.com/coinmonks/defi-sandwich-attack-explain-776f6f43b2fd

**Comment by greyireland** [comment]
I extended the strategy trait with channel, which does not block the asynchronous process
