### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by mteam88** [paradigmxyz/artemis#9]
I want to view the docs (docs.rs) online.

**Comment by 0xJepsen** [comment]
This is only possible if all dependencies are also on crates.io, looks like 

```
opensea-stream = { git = "https://github.com/FrankieIsLost/opensea-stream-rs"}
ethers-flashbots = { git = "https://github.com/FrankieIsLost/ethers-flashbots", features = ["rustls"] }
```
would need to be published first, maybe a few others

**Comment by mteam88** [comment]
@0xJepsen Yep, I'll close this for now.
